import { type PrismaClient } from "@prisma/client";

const CATEGORY_DATA = [
  ...new Set([
    "Albanian",
    "Arabic",
    "Basque",
    "Bulgarian",
    "Byelorussian",
    "Catalan",
    "Chinese",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "Dutch",
    "English",
    "Estonian",
    "Finnish",
    "French",
    "Gaelic",
    "Georgian",
    "German",
    "Greek",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Indonesian",
    "Italian",
    "Japanese",
    "Korean",
    "Latin",
    "Latvian",
    "Lithuanian",
    "Macedonian",
    "Malaysian",
    "Norwegian",
    "Persian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Russian",
    "Serbian",
    "Slovak",
    "Slovenian",
    "Spanish",
    "Swedish",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Vietnamese",
    "Other",
  ]),
];

export async function seedCategories(prisma: PrismaClient) {
  await prisma.category.createMany({
    data: CATEGORY_DATA.map((name) => ({ name })),
  });
}
